### ISSUE TITLE
2022-01-29 SpringBoot 설정

### ISSUE THREAD

**Issue by BaekJae** [BaekJae/remind#3]
## 2022-01-29 SpringBoot 뼈대 설정을 마쳤습니다.

**기본 설정**
IDE - Intellij Ultimate
Type: Maven
Packaging: Jar
Java Version:11

**플러그인(의존성)**
Spring Boot DevTools
Lombok

Spring Web
Spring Session
Spring Web Services

Spring Security

Spring Data JDBC
MyBatis Framework
MySQL Driver
***

## 초기 세팅 방법

1. 기존 프로젝트를 Clone 받으신 분들은 git pull 실행해주세요.

2. resource 부분에 database.properties 추가하고, 아래와 같은 정보를 입력해주세요.
입력하실 때 [] 빼고 입력하세요!
```properties
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:[포트번호(기본:3306)]/[DB이름]?serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=[DB 아이디]
spring.datasource.password=[DB password]
```
3. src -> main -> java -> com.team5.remind 안에 RemindApplication 실행
4. 아래와 같은 창이 뜨면 성공
![image](https://user-images.githubusercontent.com/29000892/151596582-101d403c-ebf3-4cc1-8015-8818c5de2aff.png)
***
## 별도 하고 싶은 말
프로젝트를 새로 생성하셔서 작업하는 편이 나으실 수도 있을 것이라 생각됩니다.
.gitignore에 들어간 자료가 생각보다 많습니다.

**Comment by iamjongholee** [comment]
감사합니다

**Comment by BaekJae** [comment]
**Create database [DB명];**
- 생성 완료 메시지 확인

**Use Database [위에서 생성한 DB명];**
- Database changed 명령 출력

mysql 콘솔이나 Workbench에서 위 명령 실행 후 SQL 파일 실행 바랍니다.

**Comment by BaekJae** [comment]
2022-02-04

- 프로젝트 타입 Maven -> Gradle로 변경함
